---
title: "Thiết kế tài liệu với RMarkdown"
subtitle: "(<span style=\"text-decoration: underline\">**D**</span>esign <span style=\"text-decoration: underline\">**D**</span>ocuments with <span style=\"text-decoration: underline\">**RMarkdown**</span>)"
author: "Trát Quang Thụy"
date: "Ngày 20/2/2020"
output: 
  html_document: 
    code_download: yes
    code_folding: show
    css: Style.css
    df_print: kable
    highlight: haddock
    keep_md: yes
    includes:
      in_header: _header.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

<div class="logs">
<div class="logs-caption">Logs</div>
<div class="logs-content scroll">
**18.2.2020:**

- Thêm `Navigation Bars`.

- Thêm trang "*6. Equation*": <a target="_parent" href="https://rpubs.com/BabyMouse/ddrEquation">https://rpubs.com/BabyMouse/ddrEquation</a>

**3.2.2020:**

- Thêm trang "*Phụ lục 1: Các bảng mã*": <a target="_parent" href="https://rpubs.com/BabyMouse/ddrEncodingTables">https://rpubs.com/BabyMouse/ddrEncodingTables</a>

**28.1.2020:**

- Thêm trang "*Giới thiệu*": <a target="_parent" href="https://rpubs.com/BabyMouse/ddrIntroduction">https://rpubs.com/BabyMouse/ddrIntroduction</a>

**22.1.2020:**

- Thêm "*Mục lục*" và upload `RPubs`.

- RPubs: <a target="_parent" href="https://rpubs.com/BabyMouse/ddRMarkdown">https://rpubs.com/BabyMouse/ddRMarkdown</a>

**19.1.2020:**

- Khởi tạo project và upload lên `GitHub`.

- GitHub: <a target="_parent" href="https://github.com/BabyMouse/ddRMarkdown">https://github.com/BabyMouse/ddRMarkdown</a>

</div></div>
<br/>

# **<a target="_parent" href="https://rpubs.com/BabyMouse/ddRMarkdown">Mục lục</a>**

<br/>

## **Cám ơn**

<br/>

## **Phần 1:** Giới thiệu

### 0. Giới thiệu tổng quan: <a target="_parent" href="https://rpubs.com/BabyMouse/ddrIntroduction">ddrIntroduction</a> (<span class="update">28.1.2020</span>)

* Giới thiệu về dự án
	
* Mục tiêu: Visualization nhưng thiên về Design (kĩ thuật, không phải mĩ thuật) với phạm vi public lên RPubs.
	
* Qui ước giao tiếp (protocol): Người - Người, Người - Máy
	
	* Xưng hô
	* Ngôn ngữ Anh, Việt
	* Định dạng văn bản, tài liệu
	* Tổ chức tài liệu và cách đọc
	* Phần mềm (version tương ứng) để thực tập: VS Code (và Ext về theme, formatter, code snippets), R (cả RTools), RStudio (add-on Knitr), cả MySQL nếu cần xây dựng database.

<br/>

## Phần 2: Làm quen

### 1. Triết lí Design Documents (suy nghĩ một cách thông thái)

* Kaizen vs. Revolution ("anything goes" - Paul Karl Feyerabend)
* Chia để trị (module, component)
* Tổ chức thông tin 
	* Tính logic
	* Tính hệ thống
* Khoa học vs. Nghệ thuật
* Nguyên lí "Xây cái Toilet" (History)
* Học người đi trước ('đầu tiên và cũng là cuối cùng' - Harry Potter)
	- Tiếp nhận
	- Phân tích
	- Bắt chước
	- Tùy biến 
	- Sáng tạo 

### 2. Mã hóa thông tin trong RMarkdown 

* Nguyên lí thông tin dưới góc độ khoa học máy tính (hệ bin, hex, dec; bit, byte/ word, double words)
* Kí tự: Bảng mã ASCII (7-bit, 8-bit), UniCode
* Chuỗi kí tự: Escape string, URI
* Định dạng văn bản bằng đánh dấu (markup)
	* Markdown
	* LaTeX
	* HTML
	* CSS

### 3. Nguyên liệu chế biến Documents

* Phát thảo khung sườn (template, skeleton, pattern)
* Chọn chủ đề (theme)
* Biến tấu phong cách (style)
* Thổi hồn vào Documents (DHTML, JavaScript)
	* Batch và R functions (Bắt chước)
	* Script và Own R function (Tùy biến)
	* Language (Sáng tạo)

<br/>

## Phần 3: Làm thử

### 4. Định dạng chữ

### 5. Image, Address, Block, Code: ddrHyperText

### 6. Equation <a target="_parent" href="https://rpubs.com/BabyMouse/ddrEquation">ddrEquation</a> (<span class="update">19.2.2020</span>)

### 7. Table (kable)

### 8. Graphic (ggplot2)

<br/>

## Phụ lục

### Phụ lục 1: Các bảng mã thường dùng: <a target="_parent" href="https://rpubs.com/BabyMouse/ddrEncodingTables">ddrEncodingTables</a> (<span class="update">19.2.2020</span>)

### Phụ lục 2: Convert UniCode sang Escape string

### Phụ lục 3: Convert UniCode tổ hợp sang UniCode dựng sẵn 

### Phụ lục 4: Convert Equartion từ LaTeX sang MathML

<br/>

## Chú giải thuật ngữ Anh - Việt: ddrTerms

<br/><br/><br/><br/>



 
